export const homeObjOne = {
    id:'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction With Zero Fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/img-4.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id:'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at anytime',
    description: 'We got you covered no where you are located. All you need is a computer or phone and an internet connection.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/img-1.svg').default,
    alt: 'piggy-bank',
    dark: false,
    primary: true,
    darkText: true,
}

export const homeObjThree = {
    id:'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'join Our Team',
    headline: 'Creating and account is extremely easy',
    description: "Get everything ready and set-up under 10 minutes. All you need to do is add your information and you're good to go.",
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/img-2.svg').default,
    alt: 'Paper',
    dark: false,
    primary: true,
    darkText: true,
}